version: "3.8"

services:
  
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_DB: water_level
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
  